### ISSUE TITLE
Setting options on a session does not set the same options on the cookie sent to the client.

### ISSUE THREAD

**Issue by ananthb** [GoogleCloudPlatform/firestore-gorilla-sessions#1]
Code excerpt from the handler:

``` go
func handler(w http.ResponseWriter, r * http.Request {
        // handler code
        ...
	session.Options = &sessions.Options{
		Path:     "/",
		MaxAge:   86400 * 7,
		Secure:   true,
		HttpOnly: true,
	}
        err := session.Save(r, w)
        ...
```

Cookie properties from firefox's inspector tool:
<img width="282" alt="Screenshot 2020-03-04 at 12 34 24" src="https://user-images.githubusercontent.com/3133350/75853735-b3602180-5e14-11ea-976d-52a1521a0c4d.png">

**Comment by nllptr** [comment]
Following. I've been messing about with firestore sessions and thus far my experience is the same. If I find the problem I'll try to submit a fix.

**Comment by nllptr** [comment]
https://github.com/GoogleCloudPlatform/firestore-gorilla-sessions/blob/f42bbed1618af4066369dc46301c52cc0d3e3e1d/store.go#L153-L160

This seems to be the culprit. It does not use the session options at all. I know too little about web security to say if it's by design or not, but changing it to accept a `session.Options` parameter would make it possible to customize the cookie.
